// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: CK5Roq2dBGcRPqc72xPE7
// Component: nzY669KIVI
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import CardQa from "../../CardQa"; // plasmic-import: Jgzn7LQkpI/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_cfund_landing_page.module.css"; // plasmic-import: CK5Roq2dBGcRPqc72xPE7/projectcss
import sty from "./PlasmicFaqSection.module.css"; // plasmic-import: nzY669KIVI/css

export type PlasmicFaqSection__VariantMembers = {};

export type PlasmicFaqSection__VariantsArgs = {};
type VariantPropType = keyof PlasmicFaqSection__VariantsArgs;
export const PlasmicFaqSection__VariantProps = new Array<VariantPropType>();

export type PlasmicFaqSection__ArgsType = {};
type ArgPropType = keyof PlasmicFaqSection__ArgsType;
export const PlasmicFaqSection__ArgProps = new Array<ArgPropType>();

export type PlasmicFaqSection__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  columns?: p.Flex<"div">;
};

export interface DefaultFaqSectionProps {
  className?: string;
}

function PlasmicFaqSection__RenderFunc(props: {
  variants: PlasmicFaqSection__VariantsArgs;
  args: PlasmicFaqSection__ArgsType;
  overrides: PlasmicFaqSection__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <h1
          data-plasmic-name={"h1"}
          data-plasmic-override={overrides.h1}
          className={classNames(
            projectcss.all,
            projectcss.h1,
            projectcss.__wab_text,
            sty.h1
          )}
        >
          {"FAQ"}
        </h1>

        <div
          data-plasmic-name={"columns"}
          data-plasmic-override={overrides.columns}
          className={classNames(projectcss.all, sty.columns)}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.column___9Mc1W)}
          >
            <CardQa
              className={classNames("__wab_instance", sty.cardQa__cqnlu)}
            />

            <CardQa
              className={classNames("__wab_instance", sty.cardQa__oQhrC)}
            />

            <CardQa
              className={classNames("__wab_instance", sty.cardQa___5VVw0)}
            />

            <CardQa
              className={classNames("__wab_instance", sty.cardQa__rqeOe)}
            />
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.column__vDdus)}
          >
            <CardQa
              className={classNames("__wab_instance", sty.cardQa__y2FOs)}
            />

            <CardQa
              className={classNames("__wab_instance", sty.cardQa__hMpnA)}
            />

            <CardQa
              className={classNames("__wab_instance", sty.cardQa__xNtYo)}
            />

            <CardQa
              className={classNames("__wab_instance", sty.cardQa__p61Iz)}
            />
          </p.Stack>
        </div>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "h1", "columns"],
  freeBox: ["freeBox", "h1", "columns"],
  h1: ["h1"],
  columns: ["columns"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  h1: "h1";
  columns: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFaqSection__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFaqSection__VariantsArgs;
    args?: PlasmicFaqSection__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFaqSection__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFaqSection__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFaqSection__ArgProps,
          internalVariantPropNames: PlasmicFaqSection__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicFaqSection__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFaqSection";
  } else {
    func.displayName = `PlasmicFaqSection.${nodeName}`;
  }
  return func;
}

export const PlasmicFaqSection = Object.assign(
  // Top-level PlasmicFaqSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    h1: makeNodeComponent("h1"),
    columns: makeNodeComponent("columns"),

    // Metadata about props expected for PlasmicFaqSection
    internalVariantProps: PlasmicFaqSection__VariantProps,
    internalArgProps: PlasmicFaqSection__ArgProps
  }
);

export default PlasmicFaqSection;
/* prettier-ignore-end */
