// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";
import GlobalContextsProvider from "../components/plasmic/cfund_landing_page/PlasmicGlobalContextsProvider";
import { ScreenVariantProvider } from "../components/plasmic/cfund_landing_page/PlasmicGlobalVariant__Screen";
import { UnnamedGlobalGroupOfVariantsContext } from "../components/plasmic/cfund_landing_page/PlasmicGlobalVariant__UnnamedGlobalGroupOfVariants";
import { PlasmicLogin } from "../components/plasmic/cfund_landing_page/PlasmicLogin";
import { useRouter } from "next/router";

function Login() {
  // Use PlasmicLogin to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicLogin are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicLogin is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <UnnamedGlobalGroupOfVariantsContext.Provider value={undefined}>
      <GlobalContextsProvider>
        <ph.PageParamsProvider
          params={useRouter().query}
          query={useRouter().query}
        >
          <PlasmicLogin />
        </ph.PageParamsProvider>
      </GlobalContextsProvider>
    </UnnamedGlobalGroupOfVariantsContext.Provider>
  );
}

export default Login;
